#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root "
   exit 1
fi

OLD_HOSTNAME=$(hostname)

echo "Old hostname: ${OLD_HOSTNAME}"
echo ""
echo "Please enter new hostname:"
read NEW_HOSTNAME


echo ${NEW_HOSTNAME} > /etc/hostname
hostname ${NEW_HOSTNAME}
# Update /etc/hosts if needed
sed -i "s/${OLD_HOSTNAME}/${NEW_HOSTNAME}/g" /etc/hosts

read -p "Everything set. Do you want to Reboot now? " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
    reboot now 
fi
